# Generated by Django 3.0 on 2019-12-09 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(max_length=100, verbose_name='Movie Name')),
                ('tot_tickets', models.PositiveSmallIntegerField(default=50, verbose_name='Total Number of tickets')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ticket_num', models.PositiveSmallIntegerField()),
                ('status', models.IntegerField(choices=[(1, 'AVAILABLE'), (2, 'BOOKED')], default=2)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Movie')),
            ],
            options={
                'unique_together': {('movie', 'ticket_num')},
            },
        ),
    ]
